# Generated by Django 5.2.1 on 2025-05-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advocate_type', models.CharField(blank=True, max_length=50)),
                ('name_english', models.CharField(max_length=100)),
                ('name_bengali', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='advocate_photos/')),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('husband_or_wife_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nid_number', models.CharField(blank=True, max_length=20)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('son', models.CharField(blank=True, max_length=100)),
                ('daughter', models.CharField(blank=True, max_length=100)),
                ('nomini_name', models.CharField(blank=True, max_length=100)),
                ('nomini_address', models.TextField(blank=True)),
                ('nomini_relationship', models.CharField(blank=True, max_length=50)),
                ('nomini_phone', models.CharField(blank=True, max_length=15)),
                ('nomini_birth_year', models.PositiveIntegerField(blank=True, null=True)),
                ('nomini_nid', models.CharField(blank=True, max_length=20)),
                ('nomini_birth_certificate', models.CharField(blank=True, max_length=20)),
                ('current_address', models.TextField(blank=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('education', models.CharField(blank=True, max_length=200)),
                ('bar_registration_number', models.CharField(blank=True, max_length=50)),
                ('enrollment_date_As_lawyer', models.DateField(blank=True, null=True)),
                ('enrollment_date_As_member', models.DateField(blank=True, null=True)),
                ('is_a_ex_employee', models.BooleanField(default=False)),
                ('employment_details', models.TextField(blank=True)),
                ('is_receiing_pension', models.BooleanField(default=False)),
                ('pension_details', models.TextField(blank=True)),
                ('is_from_another_bar', models.BooleanField(default=False)),
                ('practicing_court_name', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
