# Generated by Django 5.2.1 on 2025-05-08 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_building_formmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('branch_name', models.CharField(max_length=100)),
                ('account_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renter_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('floor_no', models.CharField(max_length=10)),
                ('room_no', models.CharField(max_length=10)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('building_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renters', to='person.building')),
            ],
        ),
    ]
