# Generated by Django 5.2.1 on 2025-05-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_bank_renter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
