# Generated by Django 5.2.1 on 2025-05-11 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0004_alter_advocate_email_alter_advocate_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vokalatnama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(blank=True, max_length=255, null=True)),
                ('advocateId', models.CharField(max_length=50)),
                ('building_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('sales_date', models.DateField()),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_count', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advocate', to='person.advocate')),
            ],
        ),
        migrations.CreateModel(
            name='VokalatnamaSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_serial', models.IntegerField()),
                ('to_serial', models.IntegerField()),
                ('total', models.IntegerField()),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='sale.vokalatnama')),
            ],
        ),
    ]
