# Generated by Django 5.2.1 on 2025-05-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vokalatnama',
            name='advocate',
        ),
        migrations.AddField(
            model_name='vokalatnama',
            name='advocate_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
