# Generated by Django 5.2.1 on 2025-05-15 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_bailbond_bailbondserial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailbondserial',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bailbond_serials', to='sale.bailbond'),
        ),
    ]
