# Generated by Django 5.2.1 on 2025-05-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_alter_bailbondserial_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailbond',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bailbond',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bailbond',
            name='total_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
